import mongoose from "mongoose";
import dotenv from "dotenv";
import Course from "../models/Course.js";
import Department from "../models/Department.js";

dotenv.config();

const verify = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);

        console.log("Connected to DB");

        // 1. Fetch a Department to simulate the Frontend Selection
        let dept = await Department.findOne({ name: "CSE" });
        if (!dept) {
            console.log("⚠️ CSE Department not found. Creating it for test...");
            dept = await Department.create({
                name: "CSE",
                description: "Computer Science",
                code: "CSE-TEST"
            });
        }
        console.log(`✅ Found/Created Department: ${dept.name} (ID: ${dept._id})`);

        // 2. Simulate Frontend Payload (Sending NAME not ID)
        const newCourseData = {
            name: "Test Course " + Date.now(),
            department: dept.name, // THIS IS THE KEY FIX
            description: "Generated by verification script"
        };

        // 3. Attempt Creation (Simulating Backend Logic)
        // Note: Controller does: Course.create({ name, department, ... })

        console.log("🚀 Attempting to create course with payload:", newCourseData);

        const created = await Course.create(newCourseData);
        console.log("✅ Course Created Successfully:", created);

        // 4. Verify it was stored correctly
        const saved = await Course.findById(created._id);
        if (saved.department === "CSE") {
            console.log("✅ VERIFICATION PASSED: Department stored as 'CSE'");
        } else {
            console.error("❌ VERIFICATION FAILED: Department stored as:", saved.department);
        }

        // Cleanup
        await Course.findByIdAndDelete(created._id);
        console.log("🧹 Cleanup done");

        process.exit();
    } catch (error) {
        console.error("❌ ERROR:", error);
        process.exit(1);
    }
};

verify();
